config/routes.rb
Rails.application.routes.draw do
  

  get 'welcome/index'
  get 'startpage/display_rules'

  get 'questions/get_ques/:id' => 'questions#get_ques'

  root 'welcome#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def get_ques
	@ques = Question.find(params[:id])  
  end
end

app/controllers/startpage_controller.rb
class StartpageController < ApplicationController
  def display_rules
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/startpage_helper.rb
module StartpageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/get_ques.html.erb
<div align="left">
<% if @ques.blank? %>
<p>There are not any questions currently in the system.</p>
<% else %>
<p>These are the current questions in our system</p>
<h1>Question <%= @ques.id %></h1> 
<p>
	<%= @ques.ques %>
</p>
<ol type="A">
	<li><%= @ques.opta %> </li>
	<li><%= @ques.optb %> </li>
	<li><%= @ques.optc %> </li>
	<li><%= @ques.optd %> </li>
</ol>
<% end %>
</div>

app/views/startpage/display_rules.html.erb
<head>
<style type="text/css">
 .center {  list-style-position:inside;}
</style>
</head>
<body>
<div align="center">
<h1>Rules for the quiz!</h1>
<p>Below are the guidelines for the quiz: -</p>

<ol type="1" class="center">
	<li>Each question has one correct answer</li>
	<li>Each correct answer has +5 points</li>
	<li>Each wrong answer has -1 point</li>
</ol>

<%= link_to 'Start Quiz', :controller => "questions", :action => "get_ques", :id => '1' %>
</div>
</body>

app/views/welcome/index.html.erb
<div align="center">
<h1>Welcome</h1>
<p>Welcome!</p>
<p>To start the quiz click on the Start button</p>
<%= link_to 'Start', startpage_display_rules_url %>
</div>